cmake_minimum_required(VERSION 4.2)

project(EMKENativeAudio LANGUAGES CXX)

enable_testing()

set(EMKE_NATIVE_ARTIFACT_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/../artifacts/native/x64/Release")
set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_RELEASE "${EMKE_NATIVE_ARTIFACT_DIRECTORY}")
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE "${EMKE_NATIVE_ARTIFACT_DIRECTORY}")
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE "${EMKE_NATIVE_ARTIFACT_DIRECTORY}")

add_subdirectory(EMKE.NativeAudio)
add_subdirectory(EMKE.NativeAudio.Tests)
add_subdirectory(EMKE.AudioSmoke)
