<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../EMKE.Platform/EMKE.Platform.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource
      Include="../../packaging/compatibility.internal.json"
      Link="Compatibility/compatibility.internal.json"
      LogicalName="EMKE.Setup.compatibility.internal.json" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="EMKE.Setup.Tests" />
  </ItemGroup>

</Project>
