<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../EMKE.Platform/EMKE.Platform.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="EMKE.Setup.Tests" />
  </ItemGroup>

</Project>
