<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <VSTestTestCaseFilter
      Condition="'$(VSTestTestCaseFilter)' == ''">TestCategory!=NativeAudioNativeFake&amp;TestCategory!=NativeAudioRealDll</VSTestTestCaseFilter>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageReference Include="MSTest.TestAdapter" Version="4.0.2" />
    <PackageReference Include="MSTest.TestFramework" Version="4.0.2" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/EMKE.Application/EMKE.Application.csproj" />
    <ProjectReference Include="../../src/EMKE.Platform/EMKE.Platform.csproj" />
    <ProjectReference
      Include="../EMKE.SafeHandle.FinalizerProbe/EMKE.SafeHandle.FinalizerProbe.csproj"
      ReferenceOutputAssembly="false" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

</Project>
