#ifndef EMKE_ENDPOINT_CONTRACT_H
#define EMKE_ENDPOINT_CONTRACT_H

/*
 * Single native authority for the Windows virtual-audio ABI, endpoint property,
 * endpoint roles, and host-visible WaveRT format.
 */
#define EMKE_DRIVER_ABI 1u

#define EMKE_ENDPOINT_ROLE_PROPERTY_GUID_DATA1 0x3fa64f16
#define EMKE_ENDPOINT_ROLE_PROPERTY_GUID_DATA2 0x18af
#define EMKE_ENDPOINT_ROLE_PROPERTY_GUID_DATA3 0x4e9e
#define EMKE_ENDPOINT_ROLE_PROPERTY_GUID_DATA4_0 0xb5
#define EMKE_ENDPOINT_ROLE_PROPERTY_GUID_DATA4_1 0x38
#define EMKE_ENDPOINT_ROLE_PROPERTY_GUID_DATA4_2 0x91
#define EMKE_ENDPOINT_ROLE_PROPERTY_GUID_DATA4_3 0xc1
#define EMKE_ENDPOINT_ROLE_PROPERTY_GUID_DATA4_4 0x14
#define EMKE_ENDPOINT_ROLE_PROPERTY_GUID_DATA4_5 0x0e
#define EMKE_ENDPOINT_ROLE_PROPERTY_GUID_DATA4_6 0xc1
#define EMKE_ENDPOINT_ROLE_PROPERTY_GUID_DATA4_7 0x42
#define EMKE_ENDPOINT_ROLE_PROPERTY_PID 2u

#define EMKE_ROLE_MEETING_SPEAKER_RENDER_UTF8 "emke.meeting-speaker.render"
#define EMKE_ROLE_APP_SPEAKER_CAPTURE_UTF8 "emke.app-speaker.capture"
#define EMKE_ROLE_APP_MICROPHONE_RENDER_UTF8 "emke.app-microphone.render"
#define EMKE_ROLE_MEETING_MICROPHONE_CAPTURE_UTF8 "emke.meeting-microphone.capture"

#define EMKE_ROLE_MEETING_SPEAKER_RENDER_UTF16 L"emke.meeting-speaker.render"
#define EMKE_ROLE_APP_SPEAKER_CAPTURE_UTF16 L"emke.app-speaker.capture"
#define EMKE_ROLE_APP_MICROPHONE_RENDER_UTF16 L"emke.app-microphone.render"
#define EMKE_ROLE_MEETING_MICROPHONE_CAPTURE_UTF16 L"emke.meeting-microphone.capture"

#define EMKE_AUDIO_SAMPLE_RATE 48000u
#define EMKE_AUDIO_CHANNEL_COUNT 2u
#define EMKE_AUDIO_BITS_PER_SAMPLE 32u
#define EMKE_AUDIO_FORMAT_TAG 3u
#define EMKE_AUDIO_BLOCK_ALIGN \
  ((EMKE_AUDIO_CHANNEL_COUNT * EMKE_AUDIO_BITS_PER_SAMPLE) / 8u)
#define EMKE_AUDIO_AVG_BYTES_PER_SECOND \
  (EMKE_AUDIO_SAMPLE_RATE * EMKE_AUDIO_BLOCK_ALIGN)

#if defined(_WIN32)
#ifndef NOMINMAX
#define NOMINMAX
#endif
#if defined(_KERNEL_MODE)
#include <ntddk.h>
#else
#include <windows.h>
#endif
#include <devpropdef.h>

DEFINE_DEVPROPKEY(
    DEVPKEY_EMKE_EndpointRole,
    EMKE_ENDPOINT_ROLE_PROPERTY_GUID_DATA1,
    EMKE_ENDPOINT_ROLE_PROPERTY_GUID_DATA2,
    EMKE_ENDPOINT_ROLE_PROPERTY_GUID_DATA3,
    EMKE_ENDPOINT_ROLE_PROPERTY_GUID_DATA4_0,
    EMKE_ENDPOINT_ROLE_PROPERTY_GUID_DATA4_1,
    EMKE_ENDPOINT_ROLE_PROPERTY_GUID_DATA4_2,
    EMKE_ENDPOINT_ROLE_PROPERTY_GUID_DATA4_3,
    EMKE_ENDPOINT_ROLE_PROPERTY_GUID_DATA4_4,
    EMKE_ENDPOINT_ROLE_PROPERTY_GUID_DATA4_5,
    EMKE_ENDPOINT_ROLE_PROPERTY_GUID_DATA4_6,
    EMKE_ENDPOINT_ROLE_PROPERTY_GUID_DATA4_7,
    EMKE_ENDPOINT_ROLE_PROPERTY_PID);
#endif

#endif
